// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.RockPaperScissors
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("total_rounds")]
        public long TotalRounds { get; set; }

        [JsonProperty("player_choice_mode")]
        public string PlayerChoiceMode { get; set; }

        [JsonProperty("games")]
        public Game[] Games { get; set; }

        [JsonProperty("results")]
        public Results Results { get; set; }

        [JsonProperty("overall_winner")]
        public string OverallWinner { get; set; }

        [JsonProperty("game_rules")]
        public GameRules GameRules { get; set; }
    }

    public partial class GameRules
    {
        [JsonProperty("rock_beats")]
        public string RockBeats { get; set; }

        [JsonProperty("paper_beats")]
        public string PaperBeats { get; set; }

        [JsonProperty("scissors_beats")]
        public string ScissorsBeats { get; set; }
    }

    public partial class Game
    {
        [JsonProperty("round")]
        public long Round { get; set; }

        [JsonProperty("player_choice")]
        public string PlayerChoice { get; set; }

        [JsonProperty("player_emoji")]
        public string PlayerEmoji { get; set; }

        [JsonProperty("computer_choice")]
        public string ComputerChoice { get; set; }

        [JsonProperty("computer_emoji")]
        public string ComputerEmoji { get; set; }

        [JsonProperty("outcome")]
        public string Outcome { get; set; }

        [JsonProperty("message")]
        public string Message { get; set; }
    }

    public partial class Results
    {
        [JsonProperty("player_wins")]
        public long PlayerWins { get; set; }

        [JsonProperty("computer_wins")]
        public long ComputerWins { get; set; }

        [JsonProperty("ties")]
        public long Ties { get; set; }

        [JsonProperty("player_win_percentage")]
        public long PlayerWinPercentage { get; set; }

        [JsonProperty("computer_win_percentage")]
        public long ComputerWinPercentage { get; set; }

        [JsonProperty("tie_percentage")]
        public long TiePercentage { get; set; }
    }
}
